### ISSUE TITLE
"Only when connected" mode not working

### ISSUE THREAD

**Issue by GKid94** [d4rken-org/capod#313]
The app keeps closing in background by itself 

[Image](https://github.com/user-attachments/assets/a714b1da-eb68-4184-9e3e-69f16a581c0a)
[Image](https://github.com/user-attachments/assets/fe9c7b4f-ede7-461b-b2df-6a74a9dfbb4a)

**Comment by GKid94** [comment]
The app didn't ask me to disable it...

**Comment by GKid94** [comment]
Airpods connected and it says no device...

![Image](https://github.com/user-attachments/assets/273ba97f-2edd-4616-a272-4c5ad1458890)

**Comment by GKid94** [comment]
Says the left earbud is empty but both of them are working fine...

![Image](https://github.com/user-attachments/assets/1eb2ebd7-f91b-49b8-9735-ed5ab816bbfa)
[CAPod DebugLog - v2.17.6-rc0 (21706000) -65f9e1d- GPLAY_RELEASE).zip](https://github.com/user-attachments/files/21444764/CAPod.DebugLog.-.v2.17.6-rc0.21706000.-65f9e1d-.GPLAY_RELEASE.zip)

**Comment by d4rken** [comment]
> I do however notice when looking at the main app that about 2-3 instances of my earphones appear. Before only a single one would appear.

That's normal. The pods sometimes get out of sync when taking them out of their case (they randomize their address). But it's a different address than the one used for audio connections (which makes CAPod so difficult). Anyways I think it's unrelated.

I'm looking at some logs for a test device and I'm able to sometimes create a case where the pods are connected (audio connection visible in the system), but the Bluetooth data from CAPod does not show the device as connected. The worker then stops after 15 seconds because no relevant device is connected. This might be what we are seeing on your device, and possible @GKid94's device too.

```java
14:07:25.788 WM-WorkerWrapper                          D  Starting work for eu.darken.capod.monitor.core.worker.MonitorWorker
14:07:25.868 CAP:Monitor:Worker                        D  Monitor mode: AUTOMATIC
14:07:25.868 CAP:Monitor:Worker                        D  connectedAddresses: []
14:07:25.870 CAP:Monitor:Worker                        D  knownAddresses: [AA:AA:AA:08, AA:AA:AA:E4:0A]
14:07:25.870 CAP:Monitor:Worker                        D  No known Pods are connected, canceling worker soon.
14:07:40.873 CAP:Monitor:Worker                        D  Canceling worker now, still no Pods connected.
14:07:40.910 WM-WorkerWrapper                          D  eu.darken.capod.monitor.core.worker.MonitorWorker returned a Success {mOutputData=Data {}}.
14:07:40.925 WM-WorkerWrapper                          I  Worker result SUCCESS for Work [ id=1f51aaaa-6a7f-4adf-bc5b-8a8d06dac693, tags={ eu.darken.capod.monitor.core.worker.MonitorWorker } ]
```

Currently looking into this.

**Comment by d4rken** [comment]
#346 should fix this.

It was a racecondition.

* CAPod launches too quickly, when a device is first connecting, but not yet fully connected (as headset).
* All routines get going and check the connected devices
* But connected devices don't contain it yet because it is not fully connected yet as HEADSET
* We fail to update the connected devices list once the device is fully connected

The fix in #346 changes the code so we don't look at the low level connection events, but instead wait for the high-level events when the AirPods are connected as HEADSET.

If the timing is right, it previously just worked, and if it didn't, then it didn't. That's why I likely never noticed on my device.

Thanks for helping me fix this 🍻

**Comment by fwenny** [comment]
Its the same issue as before.
Perhaps crashing isnt the right word, but the background process closes after 15 seconds.
New patch sadly did not fix the issue.
